### ISSUE TITLE
Chyba policko na zadanie vlastnej sumy

### ISSUE THREAD

**Issue by patrikfejda** [trnavka/trnavka-web#11]
Steps:
- https://trnavka.sk/dajnato/
- tuknut v tabulke "Mesačne budem prispievať do Daj na to!" tlacitko "Pokracovat"
- zobrazi sa mi formulat
- tuknem na Ina suma

Tunak chyba policko za zadanie vlastnej sumy.
Vyzera to takto:
![image](https://user-images.githubusercontent.com/55843553/218750284-026f37c9-65e0-40e3-81eb-a5f53f04b7f1.png)

Toto iste mi robi aj zbierkach napr https://trnavka.sk/dajnato/animatori-idu-za-don-boscom/

Ked to dam do inkognita, tak to ale funguje OK

Windows Chrome  Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by filiplikavcan** [comment]
Pozri pls do browser console, ci a ake errory to hadze.

**Comment by patrikfejda** [comment]
![image](https://user-images.githubusercontent.com/55843553/218973670-456ad29c-0674-4ba0-bbfb-425624d857d7.png)
@filiplikavcan ziadny error mi nehadze, ani v networku :(

**Comment by filiplikavcan** [comment]
Skus pls este adblocker vypnut, skus v inkongnito mode a daj vediet.

**Comment by filiplikavcan** [comment]
@patrikfejda Pozri pls, ci ti to este robi. Spravil som novy release.

**Comment by patrikfejda** [comment]
@filiplikavcan uz mi to ide ok
