### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by patrikfejda** [trnavka/trnavka-web#14]
Na strankach `trnavka.sk/dajnato/nieco` mi neukazuje favicon.
to iste aj na mobile

OK
![image](https://github.com/trnavka/trnavka-web/assets/55843553/e5859285-f897-45bb-9677-4d0a26e3e924)
![image](https://github.com/trnavka/trnavka-web/assets/55843553/ef5570cb-1409-42dd-886e-050252365a13)

NOT OK
![image](https://github.com/trnavka/trnavka-web/assets/55843553/547ac608-bc35-4149-9850-f2242430e66b)
![image](https://github.com/trnavka/trnavka-web/assets/55843553/cac42c7c-ad13-4395-abcf-c0e0294d4eff)

**Comment by filiplikavcan** [comment]
Fixnute.
